"""Session export — JSON and HTML report generation."""

from __future__ import annotations

import json
from dataclasses import asdict
from datetime import datetime

from ..core.hallucination import HallucinationReport
from ..core.cost import CostReport
from ..core.stream import StreamSession


def to_json(
    session: StreamSession,
    hallucination: HallucinationReport,
    cost: CostReport,
) -> str:
    """Export a complete observatory session as JSON."""
    return json.dumps(
        {
            "exported_at": datetime.utcnow().isoformat(),
            "session": {
                "prompt": session.prompt,
                "model": session.model,
                "provider": session.provider,
                "total_tokens": session.total_tokens,
                "full_text": session.full_text,
                "avg_latency_signal": session.avg_latency_signal,
            },
            "hallucination": {
                "overall_score": hallucination.overall_score,
                "risk_level": hallucination.risk_level,
                "flag_count": len(hallucination.flags),
                "flags": [
                    {
                        "token_index": f.token_index,
                        "flag_type": f.flag_type.value,
                        "confidence": f.confidence,
                        "explanation": f.explanation,
                    }
                    for f in hallucination.flags
                ],
            },
            "cost": {
                "input_tokens": cost.input_tokens,
                "input_cost_usd": cost.input_cost_usd,
                "total_cost_usd": cost.total_cost_usd,
                "efficiency_ratio": cost.efficiency_ratio,
                "potential_savings_tokens": cost.potential_savings_tokens,
                "potential_savings_usd": cost.potential_savings_usd,
            },
        },
        indent=2,
    )


def to_html(
    session: StreamSession,
    hallucination: HallucinationReport,
    cost: CostReport,
) -> str:
    """Export a complete observatory session as a self-contained HTML report."""
    flagged = hallucination.flagged_token_indices
    token_html_parts: list[str] = []
    for token in session.tokens:
        text = token.text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        alpha = int(token.latency_signal * 200 + 55)
        bg = f"rgba(255,165,0,{token.latency_signal:.2f})" if token.index in flagged else "transparent"
        token_html_parts.append(
            f'<span style="background:{bg};border-radius:2px;padding:1px" '
            f'title="token #{token.index} latency={token.latency_signal:.2f}">{text}</span>'
        )
    token_stream_html = "".join(token_html_parts)

    flag_rows = "\n".join(
        f"<tr><td>{f.token_index}</td><td>{f.flag_type.value}</td>"
        f"<td>{f.confidence:.2f}</td><td>{f.explanation}</td></tr>"
        for f in hallucination.flags
    )
    suggestion_rows = "\n".join(
        f"<tr><td>{s.pattern}</td><td>{s.replacement}</td><td>{s.estimated_savings}</td></tr>"
        for s in cost.suggestions
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>Prompt Observatory Report</title>
<style>
body{{font-family:monospace;max-width:960px;margin:2rem auto;color:#e0e0e0;background:#1a1a1a}}
h1,h2{{color:#7ec8e3}} table{{border-collapse:collapse;width:100%}}
th,td{{border:1px solid #444;padding:6px 10px;text-align:left}}
th{{background:#2a2a2a}} .score-low{{color:#4caf50}} .score-med{{color:#ff9800}} .score-high{{color:#f44336}}
.token-stream{{line-height:2;font-size:1rem;background:#111;padding:1rem;border-radius:4px}}
</style></head>
<body>
<h1>🔭 Prompt Observatory Report</h1>
<p><b>Model:</b> {session.provider}/{session.model} &nbsp;|&nbsp;
   <b>Tokens:</b> {session.total_tokens} &nbsp;|&nbsp;
   <b>Cost:</b> ${cost.total_cost_usd:.6f}</p>

<h2>Token Stream (latency heatmap)</h2>
<div class="token-stream">{token_stream_html}</div>

<h2>Hallucination Analysis
  <span class="score-{'low' if hallucination.risk_level=='low' else 'med' if hallucination.risk_level=='medium' else 'high'}">
    [{hallucination.risk_level.upper()} RISK — {hallucination.overall_score:.2%}]
  </span>
</h2>
<table><tr><th>Token #</th><th>Flag Type</th><th>Confidence</th><th>Explanation</th></tr>
{flag_rows or "<tr><td colspan=4>No flags detected</td></tr>"}
</table>

<h2>Cost Analysis</h2>
<p>Input tokens: {cost.input_tokens} | Efficiency: {cost.efficiency_ratio:.1f} chars/token |
   Potential savings: {cost.potential_savings_tokens} tokens (${cost.potential_savings_usd:.6f})</p>
<table><tr><th>Pattern</th><th>Suggestion</th><th>Est. Savings (tokens)</th></tr>
{suggestion_rows or "<tr><td colspan=3>No compression suggestions</td></tr>"}
</table>

<hr><p style="color:#666">Generated by
<a href="https://github.com/Mattbusel/prompt-observatory" style="color:#7ec8e3">prompt-observatory</a></p>
</body></html>"""
